import { InfoObject } from 'openapi3-ts';
import pkg from '../../../package.json';

export const getFilesHeader = ({ title, description, version }: InfoObject) => [
  `Generated by ${pkg.name}`,
  `Do not edit manually.`,
  ...(title ? [title] : []),
  ...(description ? [description] : []),
  ...(version ? [`OpenAPI spec version: ${version}`] : []),
];
